version: '3.3'
services:
  recommend:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommend-image
    container_name: recommend-service
    privileged: true
    stdin_open: true
    tty: true
    user: "1000"
    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
      - PULSE_COOKIE=/tmp/pulse/cookie 
    volumes:
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - ./:/app
      - /dev:/dev
      - /run/user/1000/pulse/native:/tmp/pulse/native 
      - venv:/app/.venv/
    depends_on:
      - voicevox
    networks:
      - voice-network

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox-service
    stdin_open: true
    tty: true
    ports:
      - "50021:50021"
    networks:
      - voice-network


volumes:
  venv:
   name: venv

networks:
  voice-network:
    driver: bridge
   
