version: '3.3'
services:
  recommend:
    build:
      context: .
      dockerfile: Dockerfile
    image: recommend-image
    container_name: recommend-service
    tty: true
    stdin_open: true
    privileged: true
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /etc/pulse:/etc/pulse:ro
      - ./:/app
      - venv:/app/.venv/
      - /dev:/dev
    depends_on:
      - voicevox
    networks:
      - voice-network

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox-service
    stdin_open: true
    tty: true
    ports:
      - "50021:50021"
    networks:
      - voice-network


volumes:
  venv:
   name: venv

networks:
  voice-network:
    driver: bridge
   
